[package]
name = "progress-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lerp_demo = { path = "../../" }
macroquad = "0.3"

